service: gumroad-exp12345

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true
  environment: 
    TABLE_NAME: ${env:TABLE_NAME}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:Query
          Resource: 
            - Fn::Join:
              - ''
              - - 'arn:aws:dynamodb:us-east-1:'
                - ${env:AWS_ACCOUNT}
                - ':table/'
                - ${env:TABLE_NAME}
            - Fn::Join:
              - ''
              - - 'arn:aws:dynamodb:us-east-1:'
                - ${env:AWS_ACCOUNT}
                - ':table/'
                - ${env:TABLE_NAME}
                - /*

functions:
  GetReviews:
    handler: api/get-reviews.main
    memorySize: 128
    reservedConcurrency: 2
    events:
      - httpApi:
          method: GET
          path: /
  
  PostReview:
    handler: api/post-review.main
    memorySize: 128
    reservedConcurrency: 2
    events:
      - httpApi:
          method: POST
          path: /
  
  GetRating:
    handler: api/get-rating.main
    memorySize: 128
    reservedConcurrency: 2
    events:
      - httpApi:
          method: GET
          path: /rating

resources:
  Resources:
    UserReviewsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: postedAt
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: id # id of the product
            AttributeType: S
          - AttributeName: postedAt # 
            AttributeType: S
        Tags:
          - Key: Name
            Value: gumroad-exp12345-user-reviews

